AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Data Migration infrastructure

Parameters:
  StackTag:
    Type: String
    Default: dev
    Description: Environment tag used to namespace resources

Resources:
  # --------------- Lambda ---------------
  ReadDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "data-migration-read-data-${StackTag}"
      Handler: app.handler
      Runtime: python3.12
      CodeUri: src/read_data/
      Timeout: 600
      MemorySize: 256

  ErrorHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "data-migration-error-handler-${StackTag}"
      Handler: app.handler
      Runtime: python3.12
      CodeUri: src/error_handler/
      Timeout: 300
      MemorySize: 256

  # --------------- Step Function ---------------
  DataMigrationStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub "data-migration-${StackTag}"
      DefinitionUri: statemachine/data_migration.asl.json
      DefinitionSubstitutions:
        MigrateDataFunctionArn: !GetAtt ReadDataFunction.Arn
        ErrorHandlerFunctionArn: !GetAtt ErrorHandlerFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref ReadDataFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ErrorHandlerFunction
        - S3ReadPolicy:
            BucketName: "*"
        - Statement:
            - Effect: Allow
              Action:
                - states:StartExecution
                - states:DescribeExecution
                - states:StopExecution
              Resource: "*"
      Tracing:
        Enabled: true
          

Outputs:
  ReadDataFunctionArn:
    Description: ARN of the ReadData Lambda function
    Value: !GetAtt ReadDataFunction.Arn
  StateMachineArn:
    Description: ARN of the Data Migration Step Function
    Value: !Ref DataMigrationStateMachine
